
package Vistas;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;


/**
 *
 * @author MSI
 */

public class LoginV extends javax.swing.JFrame {


    
    public LoginV() {
        
        initComponents();
        this.setLocationRelativeTo(this);
        
        icono();
        
        ajusteImg(jlabelMenu,"src/Imagenes/menu.png");
        
        JButton [] btns = {btnIniciar_Sesion};
        for (JButton btn : btns) {
            btn.setBackground(new Color(0,204,255));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener(){
                
                @Override
                public void mouseClicked(MouseEvent e) {
                    btn.setBackground(new Color(51,153,255));
              }

                @Override
                public void mousePressed(MouseEvent e) {
                    
              }

                @Override
                public void mouseReleased(MouseEvent e) {
                    
                    
              }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(51,102,255));
             }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(0,204,255));
              }  
                
            });
        }

    }
    
    public void ajusteImg(JLabel labelnombre,String root){
    
        ImageIcon img = new ImageIcon(root) ;
        Icon icon = new  ImageIcon(img.getImage().getScaledInstance(labelnombre.getWidth(), labelnombre.getHeight(),Image.SCALE_AREA_AVERAGING));
        labelnombre.setIcon(icon);
        this.repaint();
        
    }
    
    
    public void icono(){
    
        ImageIcon icono = new ImageIcon("src/Imagenes/Logo2.jpg");
        this.setIconImage(icono.getImage());
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtLogin_Usuario = new javax.swing.JTextField();
        btnIniciar_Sesion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlabelMenu = new javax.swing.JLabel();
        btnLogin_Cancelar = new javax.swing.JButton();
        txtLogin_Contraseña1 = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setForeground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(73, 80, 87));
        jLabel6.setText("Iniciar Sesión ");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 170, 50));

        txtLogin_Usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLogin_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLogin_UsuarioActionPerformed(evt);
            }
        });
        jPanel3.add(txtLogin_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 340, 40));

        btnIniciar_Sesion.setBackground(new java.awt.Color(0, 204, 255));
        btnIniciar_Sesion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnIniciar_Sesion.setForeground(new java.awt.Color(0, 0, 0));
        btnIniciar_Sesion.setText("Aceptar");
        btnIniciar_Sesion.setBorder(null);
        btnIniciar_Sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciar_SesionActionPerformed(evt);
            }
        });
        jPanel3.add(btnIniciar_Sesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 160, 50));

        jLabel7.setForeground(new java.awt.Color(73, 80, 87));
        jLabel7.setText("Contraseña");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 20, -1));

        jlabelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/menu.png"))); // NOI18N
        jlabelMenu.setMaximumSize(new java.awt.Dimension(120, 120));
        jlabelMenu.setMinimumSize(new java.awt.Dimension(128, 120));
        jlabelMenu.setPreferredSize(jlabelMenu.getMaximumSize());
        jPanel3.add(jlabelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(426, 0, 340, 490));

        btnLogin_Cancelar.setBackground(new java.awt.Color(153, 255, 153));
        btnLogin_Cancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnLogin_Cancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnLogin_Cancelar.setText("Cancelar");
        btnLogin_Cancelar.setBorder(null);
        btnLogin_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin_CancelarActionPerformed(evt);
            }
        });
        jPanel3.add(btnLogin_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 160, 50));

        txtLogin_Contraseña1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLogin_Contraseña1.setText("jPasswordField1");
        jPanel3.add(txtLogin_Contraseña1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 340, 40));

        jLabel9.setForeground(new java.awt.Color(73, 80, 87));
        jLabel9.setText("Usuario");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jPanel2.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLogin_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLogin_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLogin_UsuarioActionPerformed

    private void btnIniciar_SesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciar_SesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIniciar_SesionActionPerformed

    private void btnLogin_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin_CancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogin_CancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new LoginV().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIniciar_Sesion;
    public javax.swing.JButton btnLogin_Cancelar;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel jlabelMenu;
    public javax.swing.JPasswordField txtLogin_Contraseña1;
    public javax.swing.JTextField txtLogin_Usuario;
    // End of variables declaration//GEN-END:variables
}
