
package Vistas;



import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author MSI
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();

        
        this.setLocationRelativeTo(this);
        
        JButton [] btns = {btnMenu_Productos,btnMenu_Empleados,btnMenu_Usuarios,btnMenu_Clientes,btnMenu_Pedidos,btnMenu_Principal};
        for (JButton btn : btns) {
            btn.setBackground(new Color(86,86,86));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener(){
                
                @Override
                public void mouseClicked(MouseEvent e) {
                    btn.setBackground(new Color(255,255,255));
                    
              }

                @Override
                public void mousePressed(MouseEvent e) {
                    
              }

                @Override
                public void mouseReleased(MouseEvent e) {
                    
                    
              }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(255,255,255));
                    btn.setForeground(new Color(0,0,0));
             }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(86,86,86));
                    btn.setForeground(new Color(255,255,255));
              }  

                
            });
            
            

        }
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        plNavegacion = new javax.swing.JPanel();
        plMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnMenu_Principal = new javax.swing.JButton();
        btnMenu_Empleados = new javax.swing.JButton();
        btnMenu_Usuarios = new javax.swing.JButton();
        btnMenu_Clientes = new javax.swing.JButton();
        btnMenu_Pedidos = new javax.swing.JButton();
        btnMenu_Productos = new javax.swing.JButton();
        btnMenu_Salir = new javax.swing.JButton();
        pnBody = new javax.swing.JPanel();
        JTpaneles = new javax.swing.JTabbedPane();
        pnPrincipal = new javax.swing.JPanel();
        pnEmp = new javax.swing.JPanel();
        txtID = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtSueldo = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        txtBuscar = new javax.swing.JTextField();
        txtSupervisor = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtEmp = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        btnActualizar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        pnUsuarios = new javax.swing.JPanel();
        txtUsuario_ID = new javax.swing.JTextField();
        txtUsuario_Nombre = new javax.swing.JTextField();
        txtUsuario_Fecha = new javax.swing.JTextField();
        btnUsuario_Nuevo = new javax.swing.JButton();
        btnUsuario_Actualizar = new javax.swing.JButton();
        btnUsuario_Cancelar = new javax.swing.JButton();
        btnUsuario_Eliminar = new javax.swing.JButton();
        btnUsuario_Editar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        txtUsuario_Buscar = new javax.swing.JTextField();
        btnUsuario_Buscar = new javax.swing.JButton();
        txtUsuario_Contraseña = new javax.swing.JTextField();
        jComboBox_Usuario = new javax.swing.JComboBox<>();
        txtIUsuario_ID_Empleado = new javax.swing.JTextField();
        pnClientes = new javax.swing.JPanel();
        txtCliente_ID = new javax.swing.JTextField();
        txtCliente_Nombre = new javax.swing.JTextField();
        txtCliente_Telefono = new javax.swing.JTextField();
        btnCliente_Nuevo = new javax.swing.JButton();
        btnCliente_Actualizar = new javax.swing.JButton();
        btnCliente_Cancelar = new javax.swing.JButton();
        btnCliente_Eliminar = new javax.swing.JButton();
        btnCliente_Editar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtClientes = new javax.swing.JTable();
        txtCliente_Buscar = new javax.swing.JTextField();
        btnCliente_Buscar = new javax.swing.JButton();
        txtCliente_Cedula = new javax.swing.JTextField();
        txtCliente_Apellidos = new javax.swing.JTextField();
        pnPedidos = new javax.swing.JPanel();
        txtPedidos_ID = new javax.swing.JTextField();
        txtPedidos_Entrega = new javax.swing.JTextField();
        txtPedidos_Descripcion = new javax.swing.JTextField();
        btnPedido_Nuevo = new javax.swing.JButton();
        btnPedido_Actualizar = new javax.swing.JButton();
        btnPedido_Cancelar = new javax.swing.JButton();
        btnPedido_Eliminar = new javax.swing.JButton();
        btnPedido_Editar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtPedidos = new javax.swing.JTable();
        txtPedido__Buscar = new javax.swing.JTextField();
        btnPedido_Buscar = new javax.swing.JButton();
        txtPedidos_Fecha_realizado = new javax.swing.JTextField();
        txtPedidos_ID_Cliente = new javax.swing.JTextField();
        txtPedidos_ID_Producto = new javax.swing.JTextField();
        pnProductos = new javax.swing.JPanel();
        txtIProducto_ID = new javax.swing.JTextField();
        txtProducto_Precio = new javax.swing.JTextField();
        txtProducto_Nombre = new javax.swing.JTextField();
        btnProducto_Nuevo = new javax.swing.JButton();
        btnProducto_Actualizar = new javax.swing.JButton();
        btnProducto_Cancelar = new javax.swing.JButton();
        btnProducto_Eliminar = new javax.swing.JButton();
        btnProducto_Editar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtProductos = new javax.swing.JTable();
        txtProductos_Buscar = new javax.swing.JTextField();
        btnProductos_Buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        plNavegacion.setLayout(new java.awt.BorderLayout());

        plMenu.setBackground(new java.awt.Color(51, 51, 51));
        plMenu.setPreferredSize(new java.awt.Dimension(150, 100));
        plMenu.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 10));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 200));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 65));

        btnMenu_Principal.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnMenu_Principal.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Principal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/file_32x32.png"))); // NOI18N
        btnMenu_Principal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenu_Principal.setPreferredSize(new java.awt.Dimension(150, 70));
        btnMenu_Principal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_PrincipalActionPerformed(evt);
            }
        });
        jPanel1.add(btnMenu_Principal);

        plMenu.add(jPanel1);

        btnMenu_Empleados.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnMenu_Empleados.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Empleados.setText("Empleados");
        btnMenu_Empleados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenu_Empleados.setPreferredSize(new java.awt.Dimension(150, 70));
        btnMenu_Empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_EmpleadosActionPerformed(evt);
            }
        });
        plMenu.add(btnMenu_Empleados);

        btnMenu_Usuarios.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnMenu_Usuarios.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Usuarios.setText("Usuarios");
        btnMenu_Usuarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenu_Usuarios.setPreferredSize(new java.awt.Dimension(150, 70));
        btnMenu_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_UsuariosActionPerformed(evt);
            }
        });
        plMenu.add(btnMenu_Usuarios);

        btnMenu_Clientes.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnMenu_Clientes.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Clientes.setText("Clientes");
        btnMenu_Clientes.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenu_Clientes.setPreferredSize(new java.awt.Dimension(150, 70));
        btnMenu_Clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_ClientesActionPerformed(evt);
            }
        });
        plMenu.add(btnMenu_Clientes);

        btnMenu_Pedidos.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnMenu_Pedidos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Pedidos.setText("Pedidos");
        btnMenu_Pedidos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenu_Pedidos.setPreferredSize(new java.awt.Dimension(150, 70));
        btnMenu_Pedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_PedidosActionPerformed(evt);
            }
        });
        plMenu.add(btnMenu_Pedidos);

        btnMenu_Productos.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnMenu_Productos.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Productos.setText("Productos");
        btnMenu_Productos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenu_Productos.setPreferredSize(new java.awt.Dimension(150, 70));
        btnMenu_Productos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_ProductosActionPerformed(evt);
            }
        });
        plMenu.add(btnMenu_Productos);

        btnMenu_Salir.setBackground(new java.awt.Color(255, 0, 0));
        btnMenu_Salir.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnMenu_Salir.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu_Salir.setText("Salir");
        btnMenu_Salir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        btnMenu_Salir.setPreferredSize(new java.awt.Dimension(150, 70));
        btnMenu_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenu_SalirActionPerformed(evt);
            }
        });
        plMenu.add(btnMenu_Salir);

        plNavegacion.add(plMenu, java.awt.BorderLayout.WEST);

        pnBody.setBackground(new java.awt.Color(255, 255, 255));
        pnBody.setLayout(new java.awt.CardLayout());

        JTpaneles.setBackground(new java.awt.Color(255, 255, 255));
        JTpaneles.setForeground(new java.awt.Color(255, 255, 255));
        JTpaneles.setTabPlacement(javax.swing.JTabbedPane.RIGHT);
        JTpaneles.setEnabled(false);
        JTpaneles.setPreferredSize(new java.awt.Dimension(1368, 786));

        pnPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        pnPrincipal.setMaximumSize(new java.awt.Dimension(0, 0));
        pnPrincipal.setMinimumSize(new java.awt.Dimension(1368, 786));
        pnPrincipal.setPreferredSize(new java.awt.Dimension(1368, 786));

        javax.swing.GroupLayout pnPrincipalLayout = new javax.swing.GroupLayout(pnPrincipal);
        pnPrincipal.setLayout(pnPrincipalLayout);
        pnPrincipalLayout.setHorizontalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1873, Short.MAX_VALUE)
        );
        pnPrincipalLayout.setVerticalGroup(
            pnPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 817, Short.MAX_VALUE)
        );

        JTpaneles.addTab("", pnPrincipal);

        pnEmp.setBackground(new java.awt.Color(255, 255, 255));
        pnEmp.setMaximumSize(new java.awt.Dimension(0, 0));
        pnEmp.setPreferredSize(new java.awt.Dimension(0, 0));

        txtID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtID.setPreferredSize(new java.awt.Dimension(87, 26));

        txtApellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtApellidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtApellidos.setPreferredSize(new java.awt.Dimension(87, 26));

        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCedula.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtCedula.setPreferredSize(new java.awt.Dimension(87, 26));

        txtSueldo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSueldo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sueldo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtSueldo.setPreferredSize(new java.awt.Dimension(87, 26));

        txtTelefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTelefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Télefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtTelefono.setPreferredSize(new java.awt.Dimension(87, 26));

        txtCargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCargo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cargo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtCargo.setPreferredSize(new java.awt.Dimension(87, 26));

        txtBuscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtBuscar.setPreferredSize(new java.awt.Dimension(87, 26));

        txtSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtSupervisor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Supervisor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtSupervisor.setPreferredSize(new java.awt.Dimension(87, 26));

        btnNuevo.setBackground(new java.awt.Color(153, 255, 255));
        btnNuevo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnNuevo.setPreferredSize(new java.awt.Dimension(150, 70));

        btnCancelar.setBackground(new java.awt.Color(153, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCancelar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnBuscar.setBackground(new java.awt.Color(153, 255, 255));
        btnBuscar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnBuscar.setPreferredSize(new java.awt.Dimension(150, 70));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jtEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Empleado", "Nombre", "Apellidos", "Cedula", "Sueldo", "Téledono", "Cargo", "ID_Supervisor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtEmp);

        btnEliminar.setBackground(new java.awt.Color(153, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEliminar.setPreferredSize(new java.awt.Dimension(150, 70));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtNombre.setPreferredSize(new java.awt.Dimension(87, 26));

        btnActualizar.setBackground(new java.awt.Color(153, 255, 255));
        btnActualizar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnActualizar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnEditar.setBackground(new java.awt.Color(153, 255, 255));
        btnEditar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnEditar.setPreferredSize(new java.awt.Dimension(150, 70));

        javax.swing.GroupLayout pnEmpLayout = new javax.swing.GroupLayout(pnEmp);
        pnEmp.setLayout(pnEmpLayout);
        pnEmpLayout.setHorizontalGroup(
            pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEmpLayout.createSequentialGroup()
                .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEmpLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSueldo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEmpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnEmpLayout.createSequentialGroup()
                                .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(82, 82, 82)
                                .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(61, 61, 61)))
                .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEmpLayout.createSequentialGroup()
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnEmpLayout.setVerticalGroup(
            pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnEmpLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnEmpLayout.createSequentialGroup()
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnEmpLayout.createSequentialGroup()
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63)
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(47, 47, 47)
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnEmpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 89, Short.MAX_VALUE))
        );

        JTpaneles.addTab("", pnEmp);

        pnUsuarios.setBackground(new java.awt.Color(255, 255, 255));
        pnUsuarios.setMaximumSize(new java.awt.Dimension(0, 0));
        pnUsuarios.setPreferredSize(new java.awt.Dimension(0, 0));

        txtUsuario_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario_ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtUsuario_ID.setPreferredSize(new java.awt.Dimension(87, 26));
        txtUsuario_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuario_IDActionPerformed(evt);
            }
        });

        txtUsuario_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario_Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtUsuario_Nombre.setMaximumSize(new java.awt.Dimension(10, 10));
        txtUsuario_Nombre.setPreferredSize(new java.awt.Dimension(87, 26));

        txtUsuario_Fecha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario_Fecha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha Registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtUsuario_Fecha.setPreferredSize(new java.awt.Dimension(87, 26));

        btnUsuario_Nuevo.setBackground(new java.awt.Color(153, 255, 255));
        btnUsuario_Nuevo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnUsuario_Nuevo.setText("Nuevo");
        btnUsuario_Nuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnUsuario_Nuevo.setPreferredSize(new java.awt.Dimension(150, 70));

        btnUsuario_Actualizar.setBackground(new java.awt.Color(153, 255, 255));
        btnUsuario_Actualizar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnUsuario_Actualizar.setText("Actualizar");
        btnUsuario_Actualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnUsuario_Actualizar.setPreferredSize(new java.awt.Dimension(150, 70));
        btnUsuario_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario_ActualizarActionPerformed(evt);
            }
        });

        btnUsuario_Cancelar.setBackground(new java.awt.Color(153, 255, 255));
        btnUsuario_Cancelar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnUsuario_Cancelar.setText("Cancelar");
        btnUsuario_Cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnUsuario_Cancelar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnUsuario_Eliminar.setBackground(new java.awt.Color(153, 255, 255));
        btnUsuario_Eliminar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnUsuario_Eliminar.setText("Eliminar");
        btnUsuario_Eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnUsuario_Eliminar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnUsuario_Editar.setBackground(new java.awt.Color(153, 255, 255));
        btnUsuario_Editar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnUsuario_Editar.setText("Editar");
        btnUsuario_Editar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnUsuario_Editar.setPreferredSize(new java.awt.Dimension(150, 70));

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Usuario", "Contraseña", "Nombre de Usuario", "Tipo de Usuario", "Fecha Registro", "Empleado Registrador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtUsuarios);

        txtUsuario_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario_Buscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtUsuario_Buscar.setPreferredSize(new java.awt.Dimension(87, 26));

        btnUsuario_Buscar.setBackground(new java.awt.Color(153, 255, 255));
        btnUsuario_Buscar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnUsuario_Buscar.setText("Buscar");
        btnUsuario_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnUsuario_Buscar.setPreferredSize(new java.awt.Dimension(150, 70));
        btnUsuario_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuario_BuscarActionPerformed(evt);
            }
        });

        txtUsuario_Contraseña.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUsuario_Contraseña.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtUsuario_Contraseña.setPreferredSize(new java.awt.Dimension(87, 26));

        jComboBox_Usuario.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Usuario.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox_Usuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador", "Normal", " " }));
        jComboBox_Usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tipo de Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        txtIUsuario_ID_Empleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIUsuario_ID_Empleado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID_Empleado Registrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtIUsuario_ID_Empleado.setPreferredSize(new java.awt.Dimension(87, 26));

        javax.swing.GroupLayout pnUsuariosLayout = new javax.swing.GroupLayout(pnUsuarios);
        pnUsuarios.setLayout(pnUsuariosLayout);
        pnUsuariosLayout.setHorizontalGroup(
            pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsuariosLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUsuario_Editar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pnUsuariosLayout.createSequentialGroup()
                            .addComponent(btnUsuario_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(82, 82, 82)
                            .addComponent(btnUsuario_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtIUsuario_ID_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsuario_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnUsuariosLayout.createSequentialGroup()
                                .addComponent(jComboBox_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUsuario_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addComponent(btnUsuario_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(btnUsuario_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addComponent(txtUsuario_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtUsuario_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addComponent(txtUsuario_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUsuario_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(594, Short.MAX_VALUE))
        );
        pnUsuariosLayout.setVerticalGroup(
            pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUsuariosLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnUsuario_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtUsuario_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4))
                    .addGroup(pnUsuariosLayout.createSequentialGroup()
                        .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtUsuario_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(txtUsuario_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUsuario_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addComponent(txtIUsuario_ID_Empleado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUsuario_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsuario_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(pnUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUsuario_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUsuario_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(btnUsuario_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        JTpaneles.addTab("", pnUsuarios);

        pnClientes.setBackground(new java.awt.Color(255, 255, 255));
        pnClientes.setMaximumSize(new java.awt.Dimension(0, 0));
        pnClientes.setPreferredSize(new java.awt.Dimension(0, 0));

        txtCliente_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCliente_ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtCliente_ID.setPreferredSize(new java.awt.Dimension(87, 26));
        txtCliente_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCliente_IDActionPerformed(evt);
            }
        });

        txtCliente_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCliente_Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtCliente_Nombre.setPreferredSize(new java.awt.Dimension(87, 26));

        txtCliente_Telefono.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCliente_Telefono.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Télefono", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtCliente_Telefono.setPreferredSize(new java.awt.Dimension(87, 26));

        btnCliente_Nuevo.setBackground(new java.awt.Color(153, 255, 255));
        btnCliente_Nuevo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnCliente_Nuevo.setText("Nuevo");
        btnCliente_Nuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCliente_Nuevo.setPreferredSize(new java.awt.Dimension(150, 70));

        btnCliente_Actualizar.setBackground(new java.awt.Color(153, 255, 255));
        btnCliente_Actualizar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnCliente_Actualizar.setText("Actualizar");
        btnCliente_Actualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCliente_Actualizar.setPreferredSize(new java.awt.Dimension(150, 70));
        btnCliente_Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente_ActualizarActionPerformed(evt);
            }
        });

        btnCliente_Cancelar.setBackground(new java.awt.Color(153, 255, 255));
        btnCliente_Cancelar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnCliente_Cancelar.setText("Cancelar");
        btnCliente_Cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCliente_Cancelar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnCliente_Eliminar.setBackground(new java.awt.Color(153, 255, 255));
        btnCliente_Eliminar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnCliente_Eliminar.setText("Eliminar");
        btnCliente_Eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCliente_Eliminar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnCliente_Editar.setBackground(new java.awt.Color(153, 255, 255));
        btnCliente_Editar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnCliente_Editar.setText("Editar");
        btnCliente_Editar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnCliente_Editar.setPreferredSize(new java.awt.Dimension(150, 70));

        jtClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Clientes", "Nombre", "Apellidos", "Cedula", "Télefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtClientes);

        txtCliente_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCliente_Buscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtCliente_Buscar.setPreferredSize(new java.awt.Dimension(87, 26));

        btnCliente_Buscar.setBackground(new java.awt.Color(153, 255, 255));
        btnCliente_Buscar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnCliente_Buscar.setText("Buscar");
        btnCliente_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnCliente_Buscar.setPreferredSize(new java.awt.Dimension(150, 70));
        btnCliente_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCliente_BuscarActionPerformed(evt);
            }
        });

        txtCliente_Cedula.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCliente_Cedula.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cedula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtCliente_Cedula.setPreferredSize(new java.awt.Dimension(87, 26));

        txtCliente_Apellidos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtCliente_Apellidos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellidos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtCliente_Apellidos.setPreferredSize(new java.awt.Dimension(87, 26));

        javax.swing.GroupLayout pnClientesLayout = new javax.swing.GroupLayout(pnClientes);
        pnClientes.setLayout(pnClientesLayout);
        pnClientesLayout.setHorizontalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnClientesLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnClientesLayout.createSequentialGroup()
                                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnCliente_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCliente_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(82, 82, 82)
                                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnCliente_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnCliente_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnCliente_Editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnClientesLayout.createSequentialGroup()
                                .addComponent(txtCliente_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCliente_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(txtCliente_Telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtCliente_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCliente_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnClientesLayout.createSequentialGroup()
                        .addComponent(txtCliente_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCliente_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(582, Short.MAX_VALUE))
        );
        pnClientesLayout.setVerticalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClientesLayout.createSequentialGroup()
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnClientesLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCliente_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCliente_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addComponent(txtCliente_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(txtCliente_Cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtCliente_Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCliente_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCliente_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCliente_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCliente_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCliente_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnClientesLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCliente_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtCliente_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        JTpaneles.addTab("", pnClientes);

        pnPedidos.setBackground(new java.awt.Color(255, 255, 255));
        pnPedidos.setMaximumSize(new java.awt.Dimension(0, 0));

        txtPedidos_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPedidos_ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtPedidos_ID.setPreferredSize(new java.awt.Dimension(87, 26));
        txtPedidos_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPedidos_IDActionPerformed(evt);
            }
        });

        txtPedidos_Entrega.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPedidos_Entrega.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de Entrega", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtPedidos_Entrega.setPreferredSize(new java.awt.Dimension(87, 26));

        txtPedidos_Descripcion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPedidos_Descripcion.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Descripcion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtPedidos_Descripcion.setPreferredSize(new java.awt.Dimension(87, 26));

        btnPedido_Nuevo.setBackground(new java.awt.Color(153, 255, 255));
        btnPedido_Nuevo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnPedido_Nuevo.setText("Nuevo");
        btnPedido_Nuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPedido_Nuevo.setPreferredSize(new java.awt.Dimension(150, 70));

        btnPedido_Actualizar.setBackground(new java.awt.Color(153, 255, 255));
        btnPedido_Actualizar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnPedido_Actualizar.setText("Actualizar");
        btnPedido_Actualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPedido_Actualizar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnPedido_Cancelar.setBackground(new java.awt.Color(153, 255, 255));
        btnPedido_Cancelar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnPedido_Cancelar.setText("Cancelar");
        btnPedido_Cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPedido_Cancelar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnPedido_Eliminar.setBackground(new java.awt.Color(153, 255, 255));
        btnPedido_Eliminar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnPedido_Eliminar.setText("Eliminar");
        btnPedido_Eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPedido_Eliminar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnPedido_Editar.setBackground(new java.awt.Color(153, 255, 255));
        btnPedido_Editar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnPedido_Editar.setText("Editar");
        btnPedido_Editar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnPedido_Editar.setPreferredSize(new java.awt.Dimension(150, 70));

        jtPedidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Pedidos", "Descripcion", "Fecha de Entrega", "Fecha pedido realizado", "ID Clientes", "ID Producto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jtPedidos);

        txtPedido__Buscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPedido__Buscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtPedido__Buscar.setPreferredSize(new java.awt.Dimension(87, 26));

        btnPedido_Buscar.setBackground(new java.awt.Color(153, 255, 255));
        btnPedido_Buscar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnPedido_Buscar.setText("Buscar");
        btnPedido_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnPedido_Buscar.setPreferredSize(new java.awt.Dimension(150, 70));
        btnPedido_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPedido_BuscarActionPerformed(evt);
            }
        });

        txtPedidos_Fecha_realizado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPedidos_Fecha_realizado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Fecha de pedido", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtPedidos_Fecha_realizado.setPreferredSize(new java.awt.Dimension(87, 26));

        txtPedidos_ID_Cliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPedidos_ID_Cliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtPedidos_ID_Cliente.setPreferredSize(new java.awt.Dimension(87, 26));

        txtPedidos_ID_Producto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPedidos_ID_Producto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtPedidos_ID_Producto.setPreferredSize(new java.awt.Dimension(87, 26));

        javax.swing.GroupLayout pnPedidosLayout = new javax.swing.GroupLayout(pnPedidos);
        pnPedidos.setLayout(pnPedidosLayout);
        pnPedidosLayout.setHorizontalGroup(
            pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPedidosLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPedidosLayout.createSequentialGroup()
                        .addComponent(txtPedidos_ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPedidos_ID_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtPedidos_Descripcion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtPedidos_ID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPedido_Editar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnPedidosLayout.createSequentialGroup()
                        .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnPedido_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPedido_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(82, 82, 82)
                        .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPedido_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedido_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addComponent(txtPedidos_Entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtPedidos_Fecha_realizado, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addComponent(txtPedido__Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnPedido_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(562, Short.MAX_VALUE))
        );
        pnPedidosLayout.setVerticalGroup(
            pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnPedidosLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnPedido_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPedido__Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnPedidosLayout.createSequentialGroup()
                        .addComponent(txtPedidos_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(txtPedidos_Descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPedidos_Entrega, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPedidos_Fecha_realizado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPedidos_ID_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPedidos_ID_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPedido_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedido_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(pnPedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPedido_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPedido_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(btnPedido_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        JTpaneles.addTab("", pnPedidos);

        pnProductos.setBackground(new java.awt.Color(255, 255, 255));
        pnProductos.setMaximumSize(new java.awt.Dimension(0, 0));
        pnProductos.setPreferredSize(new java.awt.Dimension(0, 0));

        txtIProducto_ID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtIProducto_ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtIProducto_ID.setPreferredSize(new java.awt.Dimension(87, 26));
        txtIProducto_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIProducto_IDActionPerformed(evt);
            }
        });

        txtProducto_Precio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtProducto_Precio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Precio", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtProducto_Precio.setPreferredSize(new java.awt.Dimension(87, 26));

        txtProducto_Nombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtProducto_Nombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N
        txtProducto_Nombre.setPreferredSize(new java.awt.Dimension(87, 26));

        btnProducto_Nuevo.setBackground(new java.awt.Color(153, 255, 255));
        btnProducto_Nuevo.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnProducto_Nuevo.setText("Nuevo");
        btnProducto_Nuevo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnProducto_Nuevo.setPreferredSize(new java.awt.Dimension(150, 70));

        btnProducto_Actualizar.setBackground(new java.awt.Color(153, 255, 255));
        btnProducto_Actualizar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnProducto_Actualizar.setText("Actualizar");
        btnProducto_Actualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnProducto_Actualizar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnProducto_Cancelar.setBackground(new java.awt.Color(153, 255, 255));
        btnProducto_Cancelar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnProducto_Cancelar.setText("Cancelar");
        btnProducto_Cancelar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnProducto_Cancelar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnProducto_Eliminar.setBackground(new java.awt.Color(153, 255, 255));
        btnProducto_Eliminar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnProducto_Eliminar.setText("Eliminar");
        btnProducto_Eliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnProducto_Eliminar.setPreferredSize(new java.awt.Dimension(150, 70));

        btnProducto_Editar.setBackground(new java.awt.Color(153, 255, 255));
        btnProducto_Editar.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnProducto_Editar.setText("Editar");
        btnProducto_Editar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        btnProducto_Editar.setPreferredSize(new java.awt.Dimension(150, 70));

        jtProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID_Producto", "Nombre", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtProductos);

        txtProductos_Buscar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtProductos_Buscar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N
        txtProductos_Buscar.setPreferredSize(new java.awt.Dimension(87, 26));

        btnProductos_Buscar.setBackground(new java.awt.Color(153, 255, 255));
        btnProductos_Buscar.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        btnProductos_Buscar.setText("Buscar");
        btnProductos_Buscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnProductos_Buscar.setPreferredSize(new java.awt.Dimension(150, 70));
        btnProductos_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductos_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnProductosLayout = new javax.swing.GroupLayout(pnProductos);
        pnProductos.setLayout(pnProductosLayout);
        pnProductosLayout.setHorizontalGroup(
            pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProductosLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnProductosLayout.createSequentialGroup()
                            .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(btnProducto_Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnProducto_Nuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(82, 82, 82)
                            .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnProducto_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnProducto_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtProducto_Precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtProducto_Nombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtIProducto_ID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnProducto_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76)
                .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnProductosLayout.createSequentialGroup()
                        .addComponent(txtProductos_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnProductos_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 790, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnProductosLayout.setVerticalGroup(
            pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProductosLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnProductosLayout.createSequentialGroup()
                        .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnProductos_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProductos_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnProductosLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(txtIProducto_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(txtProducto_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(txtProducto_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProducto_Nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProducto_Actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(pnProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProducto_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProducto_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(54, 54, 54)
                        .addComponent(btnProducto_Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JTpaneles.addTab("", pnProductos);

        pnBody.add(JTpaneles, "card8");

        plNavegacion.add(pnBody, java.awt.BorderLayout.CENTER);

        getContentPane().add(plNavegacion, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenu_EmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_EmpleadosActionPerformed
        

        JTpaneles.setSelectedIndex(1);
        
        
    }//GEN-LAST:event_btnMenu_EmpleadosActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnProductos_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductos_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnProductos_BuscarActionPerformed

    private void txtIProducto_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIProducto_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIProducto_IDActionPerformed

    private void txtCliente_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCliente_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCliente_IDActionPerformed

    private void btnCliente_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCliente_BuscarActionPerformed

    private void btnCliente_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCliente_ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCliente_ActualizarActionPerformed

    private void txtUsuario_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuario_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuario_IDActionPerformed

    private void btnUsuario_ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario_ActualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuario_ActualizarActionPerformed

    private void btnUsuario_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuario_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUsuario_BuscarActionPerformed

    private void txtPedidos_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPedidos_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPedidos_IDActionPerformed

    private void btnPedido_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPedido_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPedido_BuscarActionPerformed

    private void btnMenu_PrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_PrincipalActionPerformed
       
        
        JTpaneles.setSelectedIndex(0);
        
        
        
    }//GEN-LAST:event_btnMenu_PrincipalActionPerformed

    private void btnMenu_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_UsuariosActionPerformed
        
        JTpaneles.setSelectedIndex(2);
        
    }//GEN-LAST:event_btnMenu_UsuariosActionPerformed

    private void btnMenu_ClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_ClientesActionPerformed
        
        JTpaneles.setSelectedIndex(3);
        
    }//GEN-LAST:event_btnMenu_ClientesActionPerformed

    private void btnMenu_PedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_PedidosActionPerformed
       
        JTpaneles.setSelectedIndex(4);
        
    }//GEN-LAST:event_btnMenu_PedidosActionPerformed

    private void btnMenu_ProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_ProductosActionPerformed
        
        JTpaneles.setSelectedIndex(5);
        
    }//GEN-LAST:event_btnMenu_ProductosActionPerformed

    private void btnMenu_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenu_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMenu_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane JTpaneles;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnBuscar;
    public javax.swing.JButton btnCancelar;
    public javax.swing.JButton btnCliente_Actualizar;
    public javax.swing.JButton btnCliente_Buscar;
    public javax.swing.JButton btnCliente_Cancelar;
    public javax.swing.JButton btnCliente_Editar;
    public javax.swing.JButton btnCliente_Eliminar;
    public javax.swing.JButton btnCliente_Nuevo;
    public javax.swing.JButton btnEditar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnMenu_Clientes;
    public javax.swing.JButton btnMenu_Empleados;
    public javax.swing.JButton btnMenu_Pedidos;
    public javax.swing.JButton btnMenu_Principal;
    public javax.swing.JButton btnMenu_Productos;
    public javax.swing.JButton btnMenu_Salir;
    public javax.swing.JButton btnMenu_Usuarios;
    public javax.swing.JButton btnNuevo;
    public javax.swing.JButton btnPedido_Actualizar;
    public javax.swing.JButton btnPedido_Buscar;
    public javax.swing.JButton btnPedido_Cancelar;
    public javax.swing.JButton btnPedido_Editar;
    public javax.swing.JButton btnPedido_Eliminar;
    public javax.swing.JButton btnPedido_Nuevo;
    public javax.swing.JButton btnProducto_Actualizar;
    public javax.swing.JButton btnProducto_Cancelar;
    public javax.swing.JButton btnProducto_Editar;
    public javax.swing.JButton btnProducto_Eliminar;
    public javax.swing.JButton btnProducto_Nuevo;
    public javax.swing.JButton btnProductos_Buscar;
    public javax.swing.JButton btnUsuario_Actualizar;
    public javax.swing.JButton btnUsuario_Buscar;
    public javax.swing.JButton btnUsuario_Cancelar;
    public javax.swing.JButton btnUsuario_Editar;
    public javax.swing.JButton btnUsuario_Eliminar;
    public javax.swing.JButton btnUsuario_Nuevo;
    public javax.swing.JComboBox<String> jComboBox_Usuario;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public javax.swing.JTable jtClientes;
    public javax.swing.JTable jtEmp;
    public javax.swing.JTable jtPedidos;
    public javax.swing.JTable jtProductos;
    public javax.swing.JTable jtUsuarios;
    private javax.swing.JPanel plMenu;
    private javax.swing.JPanel plNavegacion;
    public javax.swing.JPanel pnBody;
    public javax.swing.JPanel pnClientes;
    public javax.swing.JPanel pnEmp;
    private javax.swing.JPanel pnPedidos;
    public javax.swing.JPanel pnPrincipal;
    public javax.swing.JPanel pnProductos;
    public javax.swing.JPanel pnUsuarios;
    public javax.swing.JTextField txtApellidos;
    public javax.swing.JTextField txtBuscar;
    public javax.swing.JTextField txtCargo;
    public javax.swing.JTextField txtCedula;
    public javax.swing.JTextField txtCliente_Apellidos;
    public javax.swing.JTextField txtCliente_Buscar;
    public javax.swing.JTextField txtCliente_Cedula;
    public javax.swing.JTextField txtCliente_ID;
    public javax.swing.JTextField txtCliente_Nombre;
    public javax.swing.JTextField txtCliente_Telefono;
    public javax.swing.JTextField txtID;
    public javax.swing.JTextField txtIProducto_ID;
    public javax.swing.JTextField txtIUsuario_ID_Empleado;
    public javax.swing.JTextField txtNombre;
    public javax.swing.JTextField txtPedido__Buscar;
    public javax.swing.JTextField txtPedidos_Descripcion;
    public javax.swing.JTextField txtPedidos_Entrega;
    public javax.swing.JTextField txtPedidos_Fecha_realizado;
    public javax.swing.JTextField txtPedidos_ID;
    public javax.swing.JTextField txtPedidos_ID_Cliente;
    public javax.swing.JTextField txtPedidos_ID_Producto;
    public javax.swing.JTextField txtProducto_Nombre;
    public javax.swing.JTextField txtProducto_Precio;
    public javax.swing.JTextField txtProductos_Buscar;
    public javax.swing.JTextField txtSueldo;
    public javax.swing.JTextField txtSupervisor;
    public javax.swing.JTextField txtTelefono;
    public javax.swing.JTextField txtUsuario_Buscar;
    public javax.swing.JTextField txtUsuario_Contraseña;
    public javax.swing.JTextField txtUsuario_Fecha;
    public javax.swing.JTextField txtUsuario_ID;
    public javax.swing.JTextField txtUsuario_Nombre;
    // End of variables declaration//GEN-END:variables
}
